
INSERT INTO MINION (NAME, EVIL_MASTER) VALUES ('Stuart', 1);
INSERT INTO MINION (NAME, EVIL_MASTER) VALUES ('Donnie', 1);
INSERT INTO MINION (NAME, EVIL_MASTER) VALUES ('Bob', 1);
INSERT INTO MINION (NAME, EVIL_MASTER) VALUES ('Ken', 1);
INSERT INTO MINION (NAME, EVIL_MASTER) VALUES ('Kevin', 1);