CREATE TABLE PERSON
(
    ID   IDENTITY PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE MINION
(
    ID             IDENTITY PRIMARY KEY,
    NAME           VARCHAR(255),
    EVIL_MASTER    BIGINT,
    CONSTRAINT FK_MINION_PERSON FOREIGN KEY (EVIL_MASTER) REFERENCES PERSON
);
