/*
 * This file is generated by jOOQ.
 */
package example.springdata.jdbc.basics.simpleentity.domain;


import example.springdata.jdbc.basics.simpleentity.domain.tables.Category;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CATEGORY</code>.
     */
    public static final Category CATEGORY = example.springdata.jdbc.basics.simpleentity.domain.tables.Category.CATEGORY;
}
